name: Build and Release luci-theme-peditx Apk

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  target: "qualcommax-ipq60xx"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd build-essential libncurses5-dev gawk git gettext unzip zlib1g-dev file python3 python3-distutils curl

      - name: Setup OpenWrt SDK
        run: |
          target="${{ env.target }}"
          target_prefix=${target%%-*}
          target_suffix=${target#*-}
          url_sdk="https://downloads.openwrt.org/snapshots/targets/$target_prefix/$target_suffix/openwrt-sdk-${target}_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          wget $url_sdk
          file_name=$(echo $url_sdk | awk -F/ '{print $NF}')
          mkdir sdk && tar --zstd -xvf $file_name -C sdk --strip-components=1
          cd sdk  
          echo "src-git packages https://github.com/openwrt/packages.git" > feeds.conf.default
          echo "src-git luci https://github.com/openwrt/luci.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Add luci-theme-peditx package
        run: |
          cd sdk/package
          git clone https://github.com/peditx/luci-theme-peditx
          cd .. 
          echo "CONFIG_PACKAGE_luci-theme-peditx=m" >> .config
      - name: Build luci-theme-peditx
        run: |
          cd sdk
          make defconfig
          make package/luci-theme-peditx/compile -j$(nproc)
      - name: Save luci-theme-peditx package
        run: |
          cd sdk
          mkdir -p artifacts
          find bin/packages/*/base/ -name "*.apk" -exec cp {} artifacts/ \;

      - name: Upload luci-theme-peditx package
        uses: actions/upload-artifact@v3
        with:
          name: luci-theme-peditx-packages
          path: sdk/bin


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.5
          name: luci-theme-peditx release - ${{env.timestamp}}
          body: latest release of luci-theme-peditx theme for OpenWrt.
          files: sdk/artifacts/luci-theme-peditx*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          timestamp: ${{ github.run_id }}
